# Generated by Django 3.0.6 on 2020-05-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familieName', models.CharField(default='', max_length=200, verbose_name='Family')),
                ('surName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Surname')),
                ('nickName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nickname')),
                ('caseType', models.CharField(default='', max_length=200, verbose_name='Type of Case')),
                ('phoneContact', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('appointmentDate', models.DateTimeField(verbose_name='Last Updated')),
                ('nextRoom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Next Room Appointed')),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed'), (2, 'In Progress'), (3, 'Suspended')], default=0, verbose_name='Appointment Status')),
                ('genderMale', models.BooleanField(default=True, verbose_name='Gender is Male')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Extra Description and Notes')),
                ('lastUpdatedDate', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Creation')),
            ],
        ),
    ]
