# Generated by Django 3.0.6 on 2020-05-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hide by default'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateTimeField(verbose_name='Next Appointment Time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='nextRoom',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Next Appointed Room'),
        ),
    ]
