# Generated by Django 3.0.6 on 2020-05-15 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20200514_0714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['id']},
        ),
    ]
